<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_ObslugaAlarmow" Id="{602305fb-aa33-468a-a853-cee02f62e304}" SpecialFunc="None">
    <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									13.05.2022
//	Obsługa alarmów gromadzeniedanych o wystąpieniu i archiwizacja
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
FUNCTION_BLOCK FB_ObslugaAlarmow
VAR_INPUT
	arrTablicaZdarzen						: REFERENCE TO ARRAY [1..ObslugaAlarmow_STALE.MAX_LICZBA_OBSLUGIWANYCH_ZDARZEN] OF DUT_ObslugaAlarmow_Zdarzenie;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="PobierzAktywneZdarzenia" Id="{67fc59e8-d6db-4242-a643-33c037c80891}">
      <Declaration><![CDATA[METHOD PobierzAktywneZdarzenia : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
]]></ST>
      </Implementation>
    </Method>
    <Method Name="PobierzDefinicjeZdarzen" Id="{b47a4d20-01d0-45c2-bc61-9a330cbfc97a}">
      <Declaration><![CDATA[METHOD PobierzDefinicjeZdarzen : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_ObslugaAlarmow">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_ObslugaAlarmow.PobierzAktywneZdarzenia">
      <LineId Id="6" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_ObslugaAlarmow.PobierzDefinicjeZdarzen">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>