<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_ObslugaAlarmow" Id="{602305fb-aa33-468a-a853-cee02f62e304}" SpecialFunc="None">
    <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									13.05.2022
//	Obsługa alarmów gromadzeniedanych o wystąpieniu i archiwizacja
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
FUNCTION_BLOCK FB_ObslugaAlarmow
VAR_INPUT
	arrTablicaZdarzen						: REFERENCE TO ;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_ObslugaAlarmow">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>