<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_Przycisk_NC_Podswietlany" Id="{a4d35e9d-2bf9-419f-86bb-904560e64ad0}" SpecialFunc="None">
    <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									13.05.2022
//
//	Obsługa przycisku podświetlanego
//	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
FUNCTION_BLOCK FB_Przycisk_NC_Podswietlany EXTENDS FB_Przycisk_NC
VAR
	bLampka							AT %Q*	: BOOL;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="WlaczPodswietlenie" Id="{81282c3e-9e01-4171-b730-1a76e35e675e}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									13.05.2022
//
//	Włączenie podświetlenia przycisku
//	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
METHOD WlaczPodswietlenie
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[bLampka										:= TRUE;
]]></ST>
      </Implementation>
    </Method>
    <Method Name="WylaczPodswietlenie" Id="{3e73d794-83dc-4f34-8239-07b6c11c7978}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									13.05.2022
//
//	Wyłączenie podświetlenia przycisku
//	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
METHOD WylaczPodswietlenie
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[bLampka										:= FALSE;
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Przycisk_NC_Podswietlany">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Przycisk_NC_Podswietlany.WlaczPodswietlenie">
      <LineId Id="5" Count="1" />
    </LineIds>
    <LineIds Name="FB_Przycisk_NC_Podswietlany.WylaczPodswietlenie">
      <LineId Id="5" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>