<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_Przycisk_NO_Podswietlany" Id="{7c3dc557-ee66-419c-83aa-f52bffe2c58f}" SpecialFunc="None">
    <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									13.05.2022
//
//	Obsługa przycisku podświetlanego
//	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
FUNCTION_BLOCK FB_Przycisk_NO_Podswietlany EXTENDS FB_Przycisk_NO
VAR
	bLampka							AT %Q*	: BOOL;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="WlaczPodswietlenie" Id="{b05c4f20-bf3d-4224-aa6b-a763e972a792}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									13.05.2022
//
//	Włączenie podświetlenia przycisku
//	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
METHOD WlaczPodswietlenie
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[bLampka										:= TRUE;
]]></ST>
      </Implementation>
    </Method>
    <Method Name="WylaczPodswietlenie" Id="{0035383d-b591-419c-8b49-be1c9d7f54ee}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									13.05.2022
//
//	Wyłączenie podświetlenia przycisku
//	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
METHOD WylaczPodswietlenie
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[bLampka										:= FALSE;
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Przycisk_NO_Podswietlany">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Przycisk_NO_Podswietlany.WlaczPodswietlenie">
      <LineId Id="5" Count="1" />
    </LineIds>
    <LineIds Name="FB_Przycisk_NO_Podswietlany.WylaczPodswietlenie">
      <LineId Id="5" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>