<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_SterowanieMaszyna" Id="{13408bd3-8145-4c5f-8343-0c104b15fb7b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SterowanieMaszyna
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_SterowanieMaszyna">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>