<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_Czujnik_NO" Id="{fe7f936a-5c93-4035-995a-e10f28bd6ad6}" SpecialFunc="None">
    <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									13.05.2022
//
//	Obsługa czujnika
//	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
FUNCTION_BLOCK FB_Czujnik_NO IMPLEMENTS I_Czujnik
VAR
	Wejscie 						AT %I* 	: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="CzyAktywny" Id="{52dbf970-d522-4bcf-b92a-05d4c8a39dcb}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									13.05.2022
//
//	Sprawdzenie czy aktywny
//	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
PROPERTY CzyAktywny : BOOL]]></Declaration>
      <Get Name="Get" Id="{b4293b22-5339-4397-9c81-45b1aba2db51}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[CzyAktywny 									:= Wejscie;
]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="FB_Czujnik_NO">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Czujnik_NO.CzyAktywny.Get">
      <LineId Id="2" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>