<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_Czujnik_NC" Id="{cf71bb48-c781-4807-8d04-665179bd48af}" SpecialFunc="None">
    <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									13.05.2022
//
//	Obsługa czujnika
//	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
FUNCTION_BLOCK FB_Czujnik_NC IMPLEMENTS I_Czujnik
VAR
	Wejscie							AT %I*	: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="CzyAktywny" Id="{d2eae55c-1b03-40b5-949c-64ef2ee19fda}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									13.05.2022
//
//	Sprawdzenie czy aktywny
//	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
PROPERTY CzyAktywny : BOOL
]]></Declaration>
      <Get Name="Get" Id="{13e30e11-5125-485e-ade0-0eaac6243855}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[CzyAktywny									:= NOT Wejscie;
]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="FB_Czujnik_NC">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Czujnik_NC.CzyAktywny.Get">
      <LineId Id="2" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>