<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_ElektrozaworCewka" Id="{606fac5f-70dc-43dc-8167-f3c1b1aef47c}" SpecialFunc="None">
    <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Sterowanie cewką
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
FUNCTION_BLOCK FB_ElektrozaworCewka
VAR
	Wyjscie							AT %Q*	: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Wlacz" Id="{eff36729-b228-4a55-8531-e9f160274bea}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									13.05.2022
//	Włączenie cewki
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
METHOD Wlacz : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Wyjscie										:= TRUE;
]]></ST>
      </Implementation>
    </Method>
    <Method Name="Wylacz" Id="{b1ce8405-f55e-4e13-85a7-457bea2892cd}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									13.05.2022
//	Wyłączenie cewki
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
METHOD Wylacz : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Wyjscie										:= FALSE;
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_ElektrozaworCewka">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_ElektrozaworCewka.Wlacz">
      <LineId Id="5" Count="1" />
    </LineIds>
    <LineIds Name="FB_ElektrozaworCewka.Wylacz">
      <LineId Id="5" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>