<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_Elektrozawor_5na2_2Cewki" Id="{3d99ae90-0092-4a28-a425-90fd1fee7a8b}" SpecialFunc="None">
    <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Obsługa elektrozaworu 5/2 bistabilny
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
FUNCTION_BLOCK FB_Elektrozawor_5na2_2Cewki IMPLEMENTS I_Elektrozawor_5na
VAR
	fbCewkaA								: FB_ElektrozaworCewka; //sterowanie wyjscie 2
	fbCewkaB								: FB_ElektrozaworCewka; //sterowanie wyjscie 4
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="WlaczWyjscie2" Id="{ca2bcd17-18ec-4a83-aa5c-76fdf107ba9a}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Włączenie cewki - wyjscie 2
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
METHOD WlaczWyjscie2 : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[fbCewkaA.Wlacz ();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="WlaczWyjscie4" Id="{6d51c73b-5893-4a11-abc8-57d8c746097f}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Włączenie cewki - wyjscie 4
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
METHOD WlaczWyjscie4 : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[fbCewkaB.Wlacz ();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="WylaczWyjscie2" Id="{5712b962-e562-463c-9277-2760aecbb3e8}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Wyłączenie cewki - wyjscie 2
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================METHOD WylaczWyjscie2 : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[fbCewkaA.Wylacz ();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="WylaczWyjscie4" Id="{aae23a92-0435-4045-b965-8391db85db8d}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Wyłączenie cewki - wyjscie 4
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
METHOD WylaczWyjscie4 : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[fbCewkaB.Wylacz ();]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Elektrozawor_5na2_2Cewki">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Elektrozawor_5na2_2Cewki.WlaczWyjscie2">
      <LineId Id="5" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Elektrozawor_5na2_2Cewki.WlaczWyjscie4">
      <LineId Id="5" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Elektrozawor_5na2_2Cewki.WylaczWyjscie2">
      <LineId Id="5" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Elektrozawor_5na2_2Cewki.WylaczWyjscie4">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>