<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_Elektrozawor_3na2_NO" Id="{a76f145e-398d-4fed-98d7-f3ef1af1e802}" SpecialFunc="None">
    <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Obsługa elektrozaworu 3/2 normalnie otwartego
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
FUNCTION_BLOCK FB_Elektrozawor_3na2_NO implements I_Elektrozawor_3na2
VAR
	fbCewka									: FB_ElektrozaworCewka;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Wlacz" Id="{27c4f4fd-ed0e-46b0-9b2e-bd9454e7f642}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Włączenie cewki - wyjscie 2
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
METHOD Wlacz
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[fbCewka.Wlacz ();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="Wylacz" Id="{317c732e-5820-4268-89c3-f41fc27c4b76}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Wyłączenie cewki - wyjscie 2
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
METHOD Wylacz
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[fbCewka.Wylacz ();
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Elektrozawor_3na2_NO">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Elektrozawor_3na2_NO.Wlacz">
      <LineId Id="5" Count="1" />
    </LineIds>
    <LineIds Name="FB_Elektrozawor_3na2_NO.Wylacz">
      <LineId Id="5" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>