<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_Elektrozawor_5na3_Odpowietrzony" Id="{f17b99e1-6967-4370-8cd2-c2384288e58c}" SpecialFunc="None">
    <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Obsługa elektrozaworu 5/3 odpowietrzony w pozycji środkowej
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
FUNCTION_BLOCK FB_Elektrozawor_5na3_Odpowietrzony IMPLEMENTS I_Elektrozawor_5na
VAR
	fbCewkaA								: FB_ElektrozaworCewka;
	fbCewkaB								: FB_ElektrozaworCewka;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="WlaczWyjscie2" Id="{05977016-e664-463d-87c0-181849a20e65}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Włączenie cewki - wyjscie 2
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================METHOD WlaczWyjscie2 : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[fbCewkaA.Wlacz ();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="WlaczWyjscie4" Id="{cc4e5290-0150-4cef-b5cd-45f8eb479fdd}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Włączenie cewki - wyjscie 4
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
METHOD WlaczWyjscie4 : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[fbCewkaB.Wlacz ();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="WylaczWyjscie2" Id="{6db52a01-b744-4f16-808b-326aaf1d575a}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Wyłączenie cewki - wyjscie 2
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================METHOD WylaczWyjscie2 : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[fbCewkaA.Wylacz ();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="WylaczWyjscie4" Id="{e3696199-e3d2-4c52-a5b4-578b6fa733f5}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Wyłączenie cewki - wyjscie 4
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
METHOD WylaczWyjscie4 : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[fbCewkaB.Wylacz ();]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Elektrozawor_5na3_Odpowietrzony">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Elektrozawor_5na3_Odpowietrzony.WlaczWyjscie2">
      <LineId Id="5" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Elektrozawor_5na3_Odpowietrzony.WlaczWyjscie4">
      <LineId Id="5" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Elektrozawor_5na3_Odpowietrzony.WylaczWyjscie2">
      <LineId Id="5" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Elektrozawor_5na3_Odpowietrzony.WylaczWyjscie4">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>