<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_Elektrozawor_5na3_Zapowietrzony" Id="{3442b49e-fb5a-45e5-929b-5abafebce8b5}" SpecialFunc="None">
    <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Obsługa elektrozaworu 5/3 zapowietrzony w pozycji środkowej
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
FUNCTION_BLOCK FB_Elektrozawor_5na3_Zapowietrzony IMPLEMENTS I_Elektrozawor_5na
VAR
	fbCewkaA								: FB_ElektrozaworCewka;
	fbCewkaB								: FB_ElektrozaworCewka;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="WlaczWyjscie2" Id="{a80d863d-1ed3-44b0-bd88-83c724491f2e}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Włączenie cewki - wyjscie 2
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
METHOD WlaczWyjscie2 : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[fbCewkaA.Wylacz ();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="WlaczWyjscie4" Id="{61e05419-a3ea-4866-9827-4c84e80e73aa}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Włączenie cewki - wyjscie 4
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
METHOD WlaczWyjscie4 : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[fbCewkaB.Wylacz ();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="WylaczWyjscie2" Id="{d13d58dc-ad63-49ea-81e8-18aa1523c24b}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Wyłączenie cewki - wyjscie 2
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
METHOD WylaczWyjscie2 : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[fbCewkaA.Wlacz ();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="WylaczWyjscie4" Id="{652189a6-d336-4f57-905f-7726f3aaa32e}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Wyłączenie cewki - wyjscie 4
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
METHOD WylaczWyjscie4 : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[fbCewkaB.Wlacz ();
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Elektrozawor_5na3_Zapowietrzony">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Elektrozawor_5na3_Zapowietrzony.WlaczWyjscie2">
      <LineId Id="5" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Elektrozawor_5na3_Zapowietrzony.WlaczWyjscie4">
      <LineId Id="5" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Elektrozawor_5na3_Zapowietrzony.WylaczWyjscie2">
      <LineId Id="5" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Elektrozawor_5na3_Zapowietrzony.WylaczWyjscie4">
      <LineId Id="5" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>