<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_Elektrozawor_5na2_1Cewka" Id="{8b33e655-5369-4414-be57-0a6015bb253a}" SpecialFunc="None">
    <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Obsługa elektrozaworu 5/2 nonostabilny
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
FUNCTION_BLOCK FB_Elektrozawor_5na2_1Cewka IMPLEMENTS I_Elektrozawor_5na
VAR
	fbCewka									: FB_ElektrozaworCewka;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="WlaczWyjscie2" Id="{0d3396d8-bc87-4f8a-ad75-eb2b4f532754}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Włączenie cewki - wyjscie 2
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
METHOD WlaczWyjscie2 : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[fbCewka.Wylacz ();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="WlaczWyjscie4" Id="{5339f3a7-5c31-4d52-a830-356d60810e60}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Włączenie cewki - wyjscie 4
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
METHOD WlaczWyjscie4 : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[fbCewka.Wlacz ();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="WylaczWyjscie2" Id="{56c7b0f9-5450-44fe-8c4b-6e9773f5fb1e}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Wyłączenie cewki - wyjscie 2
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
METHOD WylaczWyjscie2 : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[fbCewka.Wlacz ();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="WylaczWyjscie4" Id="{9f5b7b82-08fc-4311-9921-406c91d3be2f}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.02.2022
//	Wyłączenie cewki - wyjscie 4
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
METHOD WylaczWyjscie4 : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[fbCewka.Wlacz ();
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Elektrozawor_5na2_1Cewka">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Elektrozawor_5na2_1Cewka.WlaczWyjscie2">
      <LineId Id="5" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Elektrozawor_5na2_1Cewka.WlaczWyjscie4">
      <LineId Id="5" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Elektrozawor_5na2_1Cewka.WylaczWyjscie2">
      <LineId Id="5" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Elektrozawor_5na2_1Cewka.WylaczWyjscie4">
      <LineId Id="5" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>